PROGRAM MAIN
IMPLICIT NONE
CHARACTER(LEN=1) :: USERINPUT
DO
READ(*,*) USERINPUT
WRITE(*,'(A)', ADVANCE='NO') USERINPUT
WRITE(*,*) ""
IF (USERINPUT == "A") THEN
WRITE(*,'(A)', ADVANCE='NO') "BRUH"
WRITE(*,*) ""
END IF
END DO
END PROGRAM MAIN
